# 10.3

In [2]:
import numpy as np

mid_scores = np.array([10, 20, 30])
final_scores = np.array([60, 70, 80])

total = mid_scores + final_scores

print("시험성적의 합계 :", total)
print("시험성적의 평균 :", total/2)

시험성적의 합계 : [ 70  90 110]
시험성적의 평균 : [35. 45. 55.]


# 10.4

In [21]:
a = np.array([1, 2, 3])

print("Shape", a.shape)
print("nDim",a.ndim)
print("dType",a.dtype)
print("itemSize",a.itemsize)
print("Size",a.size)

Shape (3,)
nDim 1
dType int32
itemSize 4
Size 3


# 10.7

In [22]:
ages =np.array([18, 19, 25, 30, 28])

y = ages > 20
print(y)
print(ages[y])

[False False  True  True  True]
[25 30 28]


# 10.9

In [23]:
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("np_array:", np_array)
print("np_array[0, 2]:", np_array[0, 2])
print("np_array[0, 0]:", np_array[0, 0])
print("np_array[2, -1]:", np_array[2, -1])


np_array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
np_array[0, 2]: 3
np_array[0, 0]: 1
np_array[2, -1]: 9


# 10.10

In [5]:
np_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

print(np_array[0:2, 2:4])
print("-" * 10)
print(np_array[::2][::2])
print(np_array[::2, ::2])

[[3 4]
 [7 8]]
----------
[[1 2 3 4]]
[[ 1  3]
 [ 9 11]]


# 10.11

In [9]:
np_array = np.array([[1,2,3], [4,5,6], [7,8,9]])
np_array > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [11]:
np_array[ np_array > 5]

array([6, 7, 8, 9])

In [12]:
np_array[:, 2]

array([3, 6, 9])

In [13]:
np_array[:, 2] > 5

array([False,  True,  True])

In [14]:
np_array[:] % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [15]:
np_array[np_array % 2 == 0]

array([2, 4, 6, 8])

# 10.13

In [33]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [38]:
np.logspace(0, 5, 10)

array([1.00000000e+00, 3.59381366e+00, 1.29154967e+01, 4.64158883e+01,
       1.66810054e+02, 5.99484250e+02, 2.15443469e+03, 7.74263683e+03,
       2.78255940e+04, 1.00000000e+05])

# 10.14

In [47]:
np_array = np.arange(12)

print('reshape(3, 4):\n',np_array.reshape(3, 4))
print('reshape(6, -1):\n',np_array.reshape(6, -1))
print('reshape(-1, 6):\n',np_array.reshape(-1, 6))

z = np.array([[1,2,3],
             [4,5,6]])

print('flatten:', z.flatten())

reshape(3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reshape(6, -1):
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
reshape(-1, 6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
flatten: [1 2 3 4 5 6]


# 10.16

In [53]:
np.random.seed(100)

print('rand(5):',np.random.rand(5))
print('rnad(5, 3):\n', np.random.rand(5, 3))

a = 10
b = 20
print('a 부터 b 사이의 난수 5개 생성: ', (b - a) * np.random.rand(5) + a)

print('randint(1, 7, size=10):', np.random.randint(1, 7, 10))
print('randint(1, 11, size=(4, 7):\n', np.random.randint(1, 11, (4,7)))

rand(5): [0.54340494 0.27836939 0.42451759 0.84477613 0.00471886]
rnad(5, 3):
 [[0.12156912 0.67074908 0.82585276]
 [0.13670659 0.57509333 0.89132195]
 [0.20920212 0.18532822 0.10837689]
 [0.21969749 0.97862378 0.81168315]
 [0.17194101 0.81622475 0.27407375]]
a 부터 b 사이의 난수 5개 생성:  [14.31704184 19.4002982  18.17649379 13.3611195  11.75410454]
randint(1, 7, size=10): [4 1 3 2 2 4 3 6 4 1]
randint(1, 11, size=(4, 7):
 [[ 2  1  8  7  3  1  9]
 [ 3  6  2  9  2  6  5]
 [ 3  9  4  6  1 10  4]
 [ 7  4  5  8  7  4 10]]


# 10.17

In [57]:
print('randn(5):', np.random.randn(5))
print('randn(5, 4):\n', np.random.randn(5, 4))

mu = 10
sigma = 2
randoms = mu + sigma * np.random.randn(5, 4)
print('randoms: \n', randoms)

randn(5): [-2.22082499 -0.86549891 -0.11585295  0.11441064 -0.05841747]
randn(5, 4):
 [[ 0.62218721 -1.63857738  0.30287735  2.07687699]
 [-1.25948997  0.32884473 -1.20982237 -0.44113846]
 [ 1.68880619 -1.59158143 -0.11039467  1.82400113]
 [ 0.71039078 -1.74668441 -2.0157135  -0.83736279]
 [-1.050555   -0.64326693 -0.50219939 -3.00081157]]
randoms: 
 [[10.57335769 10.99761517  8.79267782 12.61788217]
 [12.55181888  7.42801384  8.74848713 10.68342159]
 [ 9.73845396  7.81670072 10.14907801 12.49649649]
 [ 9.09931417  9.30495426  9.36501945 12.02590447]
 [ 8.32360652  7.91735092  9.8254287  12.30617759]]


# 도전문제 1

In [25]:
a = np.array(range(1, 11))
b = np.array(range(10, 101, 10))

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 11  22  33  44  55  66  77  88  99 110]
[ -9 -18 -27 -36 -45 -54 -63 -72 -81 -90]
[  10   40   90  160  250  360  490  640  810 1000]
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]


# 도전문제 2

In [26]:
a = np.array(range(1, 11)) + np.array(range(10, 101, 10))

print("Shape: ", a.shape)
print("Size: ", a.size)
print("Data: ", a.data)
print("Strides: ", a.strides)

Shape:  (10,)
Size:  10
Data:  <memory at 0x00000246D744AA00>
Strides:  (4,)


# Lab 1

In [27]:
array_a = np.array(range(0, 10))
array_b = np.array(range(0, 10))
array_c = np.array(range(0, 10, 2))

print("실습 1 : array_a =", array_a)
print("실습 2 : array_b =", array_b)
print("실습 3 : array_c =", array_c)
print("실습 4:")
print("array_c의 shape :", array_c.shape)
print("array_c의 ndim :", array_c.ndim)
print("array_c의 dtype :", array_c.dtype)
print("array_c의 size :", array_c.size)
print("array_c의 itemsize :", array_c.itemsize)

실습 1 : array_a = [0 1 2 3 4 5 6 7 8 9]
실습 2 : array_b = [0 1 2 3 4 5 6 7 8 9]
실습 3 : array_c = [0 2 4 6 8]
실습 4:
array_c의 shape : (5,)
array_c의 ndim : 1
array_c의 dtype : int32
array_c의 size : 5
array_c의 itemsize : 4


# Lab 2

In [28]:
heights = [1.83, 1.76, 1.69, 1.86, 1.77, 1.73]
weights= [86, 74, 59, 95, 80, 68]

np_heights = np.array(heights)
np_weights = np.array(weights)

bmi = np_weights / (np_heights ** 2)

print("대상자들의 키:", np_heights)
print("대상들의 몸무게:", np_weights)
print("대상들의 BMI:", bmi)

print("bmi가 25이상인 경우 출력:", bmi[bmi > 25])

대상자들의 키: [1.83 1.76 1.69 1.86 1.77 1.73]
대상들의 몸무게: [86 74 59 95 80 68]
대상들의 BMI: [25.68007405 23.88946281 20.65754    27.45982194 25.53544639 22.72043837]
bmi가 25이상인 경우 출력: [25.68007405 27.45982194 25.53544639]


# Lab 3

In [19]:
import numpy as np

x = np.array([['a', 'b', 'c', 'd'],
              ['c', 'c', 'g', 'h']])

mat_a = np.array([[10, 20, 30], [10, 20, 30]])
mat_b = np.array([[2, 2, 2], [1, 2, 3]])

print(x[ x == 'c'])
print(mat_a - mat_b)

['c' 'c' 'c']
[[ 8 18 28]
 [ 9 18 27]]


In [28]:
x = np.array([[1.83, 1.76, 1.69, 1.86, 1.77, 1.73],
              [86.0, 74.0, 59.0, 95.0, 80.0, 68.0]])
y = x[0:2, 1:3]
z = x[0:2][1:3]
bmi = x[1] / x[0] ** 2

print('x shape :', x.shape)
print('y shape :', y.shape)
print('z shape :', z.shape)
print('z value :', z)
print(bmi)

x shape : (2, 6)
y shape : (2, 2)
z shape : (1, 6)
z value : [[86. 74. 59. 95. 80. 68.]]
[25.68007405 23.88946281 20.65754    27.45982194 25.53544639 22.72043837]


In [32]:
players = [[170, 76.4],
           [183, 86.2],
           [181, 78.5],
           [176, 80.1]]

np_players = np.array(players)

print('몸무게가 80 이상인 선수 정보')
print(np_players[np_players[:, 1] > 80])

print('키가 180 이상인 선수 정보')
print(np_players[np_players[:, 0] > 180])

몸무게가 80 이상인 선수 정보
[[183.   86.2]
 [176.   80.1]]
키가 180 이상인 선수 정보
[[183.   86.2]
 [181.   78.5]]
