In [20]:
import numpy as np

mid_scores = np.array([10, 20, 30])
final_scores = np.array([60, 70, 80])

total = mid_scores + final_scores

print("시험성적의 합계 :", total)
print("시험성적의 평균 :", total/2)

시험성적의 합계 : [ 70  90 110]
시험성적의 평균 : [35. 45. 55.]


# 10.4

In [21]:
a = np.array([1, 2, 3])

print("Shape", a.shape)
print("nDim",a.ndim)
print("dType",a.dtype)
print("itemSize",a.itemsize)
print("Size",a.size)

Shape (3,)
nDim 1
dType int32
itemSize 4
Size 3


# 10.7

In [22]:
ages =np.array([18, 19, 25, 30, 28])

y = ages > 20
print(y)
print(ages[y])

[False False  True  True  True]
[25 30 28]


# 10.9

In [23]:
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("np_array:", np_array)
print("np_array[0, 2]:", np_array[0, 2])
print("np_array[0, 0]:", np_array[0, 0])
print("np_array[2, -1]:", np_array[2, -1])


np_array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
np_array[0, 2]: 3
np_array[0, 0]: 1
np_array[2, -1]: 9


# 10.10

In [24]:
np_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

print(np_array[0:2, 2:4])
print("-" * 10)
print(np_array[::2][::2])
print(np_array[::2, ::2])

[[3 4]
 [7 8]]
----------
[[1 2 3 4]]
[[ 1  3]
 [ 9 11]]


# 도전문제 1

In [25]:
a = np.array(range(1, 11))
b = np.array(range(10, 101, 10))

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 11  22  33  44  55  66  77  88  99 110]
[ -9 -18 -27 -36 -45 -54 -63 -72 -81 -90]
[  10   40   90  160  250  360  490  640  810 1000]
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]


# 도전문제 2

In [26]:
a = np.array(range(1, 11)) + np.array(range(10, 101, 10))

print("Shape: ", a.shape)
print("Size: ", a.size)
print("Data: ", a.data)
print("Strides: ", a.strides)

Shape:  (10,)
Size:  10
Data:  <memory at 0x00000246D744AA00>
Strides:  (4,)


# Lab 1

In [27]:
array_a = np.array(range(0, 10))
array_b = np.array(range(0, 10))
array_c = np.array(range(0, 10, 2))

print("실습 1 : array_a =", array_a)
print("실습 2 : array_b =", array_b)
print("실습 3 : array_c =", array_c)
print("실습 4:")
print("array_c의 shape :", array_c.shape)
print("array_c의 ndim :", array_c.ndim)
print("array_c의 dtype :", array_c.dtype)
print("array_c의 size :", array_c.size)
print("array_c의 itemsize :", array_c.itemsize)

실습 1 : array_a = [0 1 2 3 4 5 6 7 8 9]
실습 2 : array_b = [0 1 2 3 4 5 6 7 8 9]
실습 3 : array_c = [0 2 4 6 8]
실습 4:
array_c의 shape : (5,)
array_c의 ndim : 1
array_c의 dtype : int32
array_c의 size : 5
array_c의 itemsize : 4


# Lab 2

In [28]:
heights = [1.83, 1.76, 1.69, 1.86, 1.77, 1.73]
weights= [86, 74, 59, 95, 80, 68]

np_heights = np.array(heights)
np_weights = np.array(weights)

bmi = np_weights / (np_heights ** 2)

print("대상자들의 키:", np_heights)
print("대상들의 몸무게:", np_weights)
print("대상들의 BMI:", bmi)

print("bmi가 25이상인 경우 출력:", bmi[bmi > 25])

대상자들의 키: [1.83 1.76 1.69 1.86 1.77 1.73]
대상들의 몸무게: [86 74 59 95 80 68]
대상들의 BMI: [25.68007405 23.88946281 20.65754    27.45982194 25.53544639 22.72043837]
bmi가 25이상인 경우 출력: [25.68007405 27.45982194 25.53544639]
